export enum ProductCategriesEnum {
	Legs = "Legs",
	Rails = "Rails",
	Stretchers = "Stretchers",
	Backrest = "Backrest",
	Armrest = "Armrest",
	Base = "Base",
	Cushion = "Cushion",
	Springs = "Springs",
	Webbing = "Webbing",
	Panels = "Panels",
	Drawers = "Drawers",
	Shelves = "Shelves",
	Slats = "Slats",
	Dowels = "Dowels",
	Screws = "Screws",
	Fasteners = "Fasteners",
	Fabric = "Fabric",
	Foam = "Foam",
	Padding = "Padding",
	Batting = "Batting",
	Clips = "Clips",
	Staples = "Staples",
	Tubing = "Tubing",
	Frames = "Frames",
	Brackets = "Brackets",
	Chair = "Chair",
}

export enum ChairsEnum {
	Arm = "Arm",
	Barrel = "Barrel",
	BarStool = "Bar-stool",
	Bath = "Bath",
	Beanbag = "Beanbag",
	Bentwood = "Bentwood",
	Berbice = "Berbice",
	BucketSeat = "Bucket seat",
	Campaign = "Campaign",
	Camp = "Camp",
	Cane = "Cane",
	Carver = "Carver",
	Corner = "Corner",
	Curule = "Curule",
	Deck = "Deck",
	Dining = "Dining",
	Directors = "Director's",
	DosADos = "Dos-à-dos",
	Easy = "Easy",
	Fauteuil = "Fauteuil",
	FiddleBack = "Fiddle-back",
}

export enum FurnitureBrands {
	Ikea = "Ikea",
	AshleyFurniture = "Ashley Furniture",
	LaZBoy = "La-Z-Boy",
	RoomsToGo = "Rooms To Go",
	HermanMiller = "Herman Miller",
	EthanAllen = "Ethan Allen",
	WestElm = "West Elm",
	Wayfair = "Wayfair",
	CrateAndBarrel = "Crate & Barrel",
	PotteryBarn = "Pottery Barn",
	RaymourAndFlanigan = "Raymour & Flanigan",
	BobsDiscountFurniture = "Bob's Discount Furniture",
	Natuzzi = "Natuzzi",
	BassettFurniture = "Bassett Furniture",
	Havertys = "Havertys",
	Bernhardt = "Bernhardt",
	Stickley = "Stickley",
	Broyhill = "Broyhill",
	Klaussner = "Klaussner",
	Thomasville = "Thomasville",
}

export enum FurnitureMaterials {
	Wood = "Wood",
	Metal = "Metal",
	Upholstery = "Upholstery",
	Wicker = "Wicker",
	Glass = "Glass",
	Plastic = "Plastic",
	Stone = "Stone",
	Rattan = "Rattan",
	Concrete = "Concrete",
	Bamboo = "Bamboo",
}

export enum RoomsEnum {
	Bedroom = "Bedroom",
	LivingRoom = "Living Room",
	Kitchen = "Kitchen",
	Bathroom = "Bathroom",
	DiningRoom = "Dining Room",
	StudyRoom = "Study Room",
}
